In [1]:
import pandas as pd

In [2]:
json = open('./dados/aluguel.json')
print(json.read())

[{"Tipo":"Quitinete","Bairro":"Copacabana","Quartos":1,"Vagas":0,"Suites":0,"Area":40,"Valor":1700.0,"Condominio":500.0,"IPTU":60.0},
{"Tipo":"Casa","Bairro":"Jardim Bot\u00e2nico","Quartos":2,"Vagas":0,"Suites":1,"Area":100,"Valor":7000.0,"Condominio":null,"IPTU":null},
{"Tipo":"Conjunto Comercial\/Sala","Bairro":"Barra da Tijuca","Quartos":0,"Vagas":4,"Suites":0,"Area":150,"Valor":5200.0,"Condominio":4020.0,"IPTU":1111.0},
{"Tipo":"Apartamento","Bairro":"Centro","Quartos":1,"Vagas":0,"Suites":0,"Area":15,"Valor":800.0,"Condominio":390.0,"IPTU":20.0},
{"Tipo":"Apartamento","Bairro":"Higien\u00f3polis","Quartos":1,"Vagas":0,"Suites":0,"Area":48,"Valor":800.0,"Condominio":230.0,"IPTU":null},
{"Tipo":"Apartamento","Bairro":"Vista Alegre","Quartos":3,"Vagas":1,"Suites":0,"Area":70,"Valor":1200.0,"Condominio":null,"IPTU":null},
{"Tipo":"Apartamento","Bairro":"Cachambi","Quartos":2,"Vagas":0,"Suites":0,"Area":50,"Valor":1300.0,"Condominio":301.0,"IPTU":17.0},
{"Tipo":"Casa de Condom\u00ednio","Bairro":"Barra da Tijuca","Quartos":5,"Vagas":4,"Suites":5,"Area":750,"Valor":22000.0,"Condominio":null,"IPTU":null},
{"Tipo":"Casa de Condom\u00ednio","Bairro":"Ramos","Quartos":2,"Vagas":2,"Suites":0,"Area":65,"Valor":1000.0,"Condominio":null,"IPTU":null},
{"Tipo":"Conjunto Comercial\/Sala","Bairro":"Centro","Quartos":0,"Vagas":3,"Suites":0,"Area":695,"Valor":35000.0,"Condominio":19193.0,"IPTU":3030.0}]

In [3]:
df_json = pd.read_json('./dados/aluguel.json')
df_json

,Area,Bairro,Condominio,IPTU,Quartos,Suites,Tipo,Vagas,Valor
0,40,Copacabana,500.0,60.0,1,0,Quitinete,0,1700
1,100,Jardim Botânico,NaN,NaN,2,1,Casa,0,7000
2,150,Barra da Tijuca,4020.0,1111.0,0,0,Conjunto Comercial/Sala,4,5200
3,15,Centro,390.0,20.0,1,0,Apartamento,0,800
4,48,Higienópolis,230.0,NaN,1,0,Apartamento,0,800
5,70,Vista Alegre,NaN,NaN,3,0,Apartamento,1,1200
6,50,Cachambi,301.0,17.0,2,0,Apartamento,0,1300
7,750,Barra da Tijuca,NaN,NaN,5,5,Casa de Condomínio,4,22000
8,65,Ramos,NaN,NaN,2,0,Casa de Condomínio,2,1000
9,695,Centro,19193.0,3030.0,0,0,Conjunto Comercial/Sala,3,35000

In [4]:
txt = open('./dados/aluguel.txt')
print(txt.read())

Tipo	Bairro	Quartos	Vagas	Suites	Area	Valor	Condominio	IPTU
Quitinete	Copacabana	1	0	0	40	1700	500	60
Casa	Jardim BotÃ¢nico	2	0	1	100	7000
Conjunto Comercial/Sala	Barra da Tijuca	0	4	0	150	5200	4020	1111
Apartamento	Centro	1	0	0	15	800	390	20
Apartamento	HigienÃ³polis	1	0	0	48	800	230
Apartamento	Vista Alegre	3	1	0	70	1200
Apartamento	Cachambi	2	0	0	50	1300	301	17
Casa de CondomÃ­nio	Barra da Tijuca	5	4	5	750	22000
Casa de CondomÃ­nio	Ramos	2	2	0	65	1000
Conjunto Comercial/Sala	Centro	0	3	0	695	35000	19193	3030

In [5]:
df_txt = pd.read_table('./dados/aluguel.txt')
df_txt

c:\users\ramon.nascimento\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  """Entry point for launching an IPython kernel.

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Quitinete,Copacabana,1,0,0,40,1700,500.0,60.0
1,Casa,Jardim Botânico,2,0,1,100,7000,NaN,NaN
2,Conjunto Comercial/Sala,Barra da Tijuca,0,4,0,150,5200,4020.0,1111.0
3,Apartamento,Centro,1,0,0,15,800,390.0,20.0
4,Apartamento,Higienópolis,1,0,0,48,800,230.0,NaN
5,Apartamento,Vista Alegre,3,1,0,70,1200,NaN,NaN
6,Apartamento,Cachambi,2,0,0,50,1300,301.0,17.0
7,Casa de Condomínio,Barra da Tijuca,5,4,5,750,22000,NaN,NaN
8,Casa de Condomínio,Ramos,2,2,0,65,1000,NaN,NaN
9,Conjunto Comercial/Sala,Centro,0,3,0,695,35000,19193.0,3030.0

In [6]:
df_xlsx = pd.read_excel('./dados/aluguel.xlsx')
df_xlsx

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Quitinete,Copacabana,1,0,0,40,1700,500.0,60.0
1,Casa,Jardim Botânico,2,0,1,100,7000,NaN,NaN
2,Conjunto Comercial/Sala,Barra da Tijuca,0,4,0,150,5200,4020.0,1111.0
3,Apartamento,Centro,1,0,0,15,800,390.0,20.0
4,Apartamento,Higienópolis,1,0,0,48,800,230.0,NaN
5,Apartamento,Vista Alegre,3,1,0,70,1200,NaN,NaN
6,Apartamento,Cachambi,2,0,0,50,1300,301.0,17.0
7,Casa de Condomínio,Barra da Tijuca,5,4,5,750,22000,NaN,NaN
8,Casa de Condomínio,Ramos,2,2,0,65,1000,NaN,NaN
9,Conjunto Comercial/Sala,Centro,0,3,0,695,35000,19193.0,3030.0

In [7]:
df_html = pd.read_html('./dados/dados_html_1.html')
df_html[0]

  FAIXA ETÁRIA UNAFISCO SAÚDE SOFT II SOFT PARTICIPATIVO      UNIQUE
0      00 A 18               R$218,99           R$192,60    R$334,48
1      19 A 23               R$263,63           R$207,67    R$380,06
2      24 A 28               R$322,44           R$224,26    R$464,39
3      29 A 33               R$402,05           R$258,63    R$566,68
4      34 A 38               R$455,17           R$306,37    R$664,61
5      39 A 43               R$489,29           R$417,93    R$742,72
6      44 A 48               R$582,65           R$495,24    R$869,47
7      49 A 53               R$718,86           R$562,64  R$1.046,29
8      54 A 58               R$908,54           R$721,00  R$1.355,74
9   59 OU MAIS             R$1.244,50         R$1.151,62  R$2.003,53

In [8]:
df_html = pd.read_html('https://unafiscosaude.org.br/site/tabelas-de-precos-dos-planos-ativos-para-comercializacao/')
df_html[0]

URLError: <urlopen error [WinError 10060] Uma tentativa de conexão falhou porque o componente conectado não respondeu
corretamente após um período de tempo ou a conexão estabelecida falhou
porque o host conectado não respondeu>

In [9]:
df_html = pd.read_html('https://www.federalreserve.gov/releases/h3/current/default.htm')
len(df_html)

URLError: <urlopen error [WinError 10060] Uma tentativa de conexão falhou porque o componente conectado não respondeu
corretamente após um período de tempo ou a conexão estabelecida falhou
porque o host conectado não respondeu>